## Exercícios

Link para Dataset: https://www.kaggle.com/datasets/matheusfreitag/gas-prices-in-brazil

In [1]:
import pandas as pd

## Neste projeto, trabalharemos com dois arquivos csvs separados, contendo informações sobre o preço da gasolina no Brasil. 

### 1. Carregue os conjuntos de dados "gasolina_2000+.csv" e "gasolina_2010+.csv" em dois DataFrames diferentes e combine-os em um único DataFrame.

In [25]:
df_petro = pd.read_csv('gasolina_2000+.csv')
df_petro2 = pd.read_csv('gasolina_2010+.csv')

df_petro = pd.concat([df_petro, df_petro2], ignore_index=True)

C:\Users\Enuk\AppData\Local\Temp\ipykernel_13356\1478209189.py:2: DtypeWarning: Columns (0: MARGEM MÉDIA REVENDA, 1: PREÇO MÉDIO DISTRIBUIÇÃO, 2: DESVIO PADRÃO DISTRIBUIÇÃO, 3: PREÇO MÍNIMO DISTRIBUIÇÃO, 4: PREÇO MÁXIMO DISTRIBUIÇÃO, 5: COEF DE VARIAÇÃO DISTRIBUIÇÃO) have mixed types. Specify dtype option on import or set low_memory=False.
  df_petro2 = pd.read_csv('gasolina_2010+.csv')

### 2.Investigue as colunas e entenda o conjunto de dados usando o head() e info()

In [31]:
#Comando Head() para mostrar as primeiras linhas do DataFrame
df_petro.head(200000)
#Comando Info() para mostrar informações sobre o DataFrame

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120819,120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120821,120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120822,120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [32]:
df_petro.info()

<class 'pandas.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 19 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     120823 non-null  int64
 1   DATA INICIAL                   120823 non-null  str
 2   DATA FINAL                     120823 non-null  str
 3   REGIÃO                         120823 non-null  str
 4   ESTADO                         120823 non-null  str
 5   PRODUTO                        120823 non-null  str
 6   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 7   UNIDADE DE MEDIDA              120823 non-null  str
 8   PREÇO MÉDIO REVENDA            120823 non-null  float64
 9   DESVIO PADRÃO REVENDA          120823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           120823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 12  MARGEM MÉDIA REVENDA           120823 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: float64(5), int64(2), object(6), str(6)
memory usage: 17.5+ MB

### 3. Selecione a terceira entrada da coluna DATA INICIAL e verifique seu tipo.

In [33]:
df_petro['DATA INICIAL']

0         2004-05-09
1         2004-05-09
2         2004-05-09
3         2004-05-09
4         2004-05-09
             ...
120818    2021-04-25
120819    2021-04-25
120820    2021-04-25
120821    2021-04-25
120822    2021-04-25
Name: DATA INICIAL, Length: 120823, dtype: str

### 4. Você deve ter percebido que as colunas DATA INICIAL e DATA FINAL estão formatadas como string. Utilizando o método pd.to_datetime(), converta ambas colunas para Timestamp / Datetime.

In [34]:
df_petro['DATA INICIAL'] = pd.to_datetime(df_petro['DATA INICIAL'], format=  '%Y-%m-%d',errors='coerce')
df_petro.info('DATA INICIAL')

<class 'pandas.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 19 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     120823 non-null  int64
 1   DATA INICIAL                   120823 non-null  datetime64[us]
 2   DATA FINAL                     120823 non-null  str
 3   REGIÃO                         120823 non-null  str
 4   ESTADO                         120823 non-null  str
 5   PRODUTO                        120823 non-null  str
 6   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 7   UNIDADE DE MEDIDA              120823 non-null  str
 8   PREÇO MÉDIO REVENDA            120823 non-null  float64
 9   DESVIO PADRÃO REVENDA          120823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           120823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 12  MARGEM MÉDIA REVENDA           120823 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: datetime64[us](1), float64(5), int64(2), object(6), str(5)
memory usage: 17.5+ MB

In [35]:
df_petro['DATA FINAL'] = pd.to_datetime(df_petro['DATA FINAL'], format=  '%Y-%m-%d',errors='coerce')
df_petro.info('DATA FINAL')

<class 'pandas.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 19 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     120823 non-null  int64
 1   DATA INICIAL                   120823 non-null  datetime64[us]
 2   DATA FINAL                     120823 non-null  datetime64[us]
 3   REGIÃO                         120823 non-null  str
 4   ESTADO                         120823 non-null  str
 5   PRODUTO                        120823 non-null  str
 6   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 7   UNIDADE DE MEDIDA              120823 non-null  str
 8   PREÇO MÉDIO REVENDA            120823 non-null  float64
 9   DESVIO PADRÃO REVENDA          120823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           120823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 12  MARGEM MÉDIA REVENDA           120823 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: datetime64[us](2), float64(5), int64(2), object(6), str(4)
memory usage: 17.5+ MB

### 5. Crie uma nova coluna para representar o ano e o mês(aaaa-mm), utilizando a coluna DATA FINAL como referência.

In [36]:
df_petro['ANO-MES'] = df_petro['DATA FINAL'].dt.to_period('M')
df_petro.info('ANO-MES')

<class 'pandas.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     120823 non-null  int64
 1   DATA INICIAL                   120823 non-null  datetime64[us]
 2   DATA FINAL                     120823 non-null  datetime64[us]
 3   REGIÃO                         120823 non-null  str
 4   ESTADO                         120823 non-null  str
 5   PRODUTO                        120823 non-null  str
 6   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 7   UNIDADE DE MEDIDA              120823 non-null  str
 8   PREÇO MÉDIO REVENDA            120823 non-null  float64
 9   DESVIO PADRÃO REVENDA          120823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           120823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 12  MARGEM MÉDIA REVENDA           120823 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
 19  ANO-MES                        120823 non-null  period[M]
dtypes: datetime64[us](2), float64(5), int64(2), object(6), period[M](1), str(4)
memory usage: 18.4+ MB

### 6. Utilizando o value_counts(), liste todos os tipos de produtos contidos na base de dados.

In [37]:
df_petro['PRODUTO'].value_counts()

PRODUTO
GASOLINA COMUM        23570
GLP                   23561
ETANOL HIDRATADO      23440
ÓLEO DIESEL           21194
GNV                   14469
ÓLEO DIESEL S10        9113
OLEO DIESEL S10        2376
OLEO DIESEL            2351
GASOLINA ADITIVADA      749
Name: count, dtype: int64

### 7. Filtre o DataFrame para obter apenas dados da 'GASOLINA COMUM'. Grave em uma nova variável.

In [38]:
df_gasolina = df_petro[df_petro['PRODUTO'] == 'GASOLINA COMUM']
df_gasolina.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO-MES
9256,12064,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,128,R$/l,2.029,0.007,1.99,2.070,0.318,0.003,1.711,0.02,1.651,1.7427,0.012,2004-05
9257,12065,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GASOLINA COMUM,395,R$/l,2.025,0.062,1.85,2.220,0.296,0.031,1.729,0.036,1.6643,1.915,0.021,2004-05
9258,12066,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,194,R$/l,2.358,0.066,2.00,2.540,0.472,0.028,1.886,0.068,1.75,2.0713,0.036,2004-05
9259,12067,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,166,R$/l,2.120,0.075,1.97,2.440,0.325,0.035,1.795,0.033,1.70701,1.9703,0.018,2004-05
9260,12068,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GASOLINA COMUM,106,R$/l,2.090,0.034,2.00,2.159,0.35,0.016,1.74,0.042,1.6789,1.918,0.024,2004-05

### 8. Qual o preço médio de revenda da gasolina em agosto de 2008?

In [39]:
df_gasolina2008 = df_gasolina[df_gasolina['ANO-MES'] == '2008-08']
df_gasolina2008['PREÇO MÉDIO REVENDA'].mean()

np.float64(2.6012444444444442)

### 9. Qual o preço médio de revenda da gasolina em maio de 2014 em São Paulo?

In [40]:
df_gasolina['ESTADO'].unique()

<StringArray>
[   'DISTRITO FEDERAL',               'GOIAS',         'MATO GROSSO',
  'MATO GROSSO DO SUL',             'ALAGOAS',               'BAHIA',
               'CEARA',            'MARANHAO',             'PARAIBA',
          'PERNAMBUCO',               'PIAUI', 'RIO GRANDE DO NORTE',
             'SERGIPE',                'ACRE',               'AMAPA',
            'AMAZONAS',                'PARA',            'RONDONIA',
             'RORAIMA',           'TOCANTINS',      'ESPIRITO SANTO',
        'MINAS GERAIS',      'RIO DE JANEIRO',           'SAO PAULO',
              'PARANA',   'RIO GRANDE DO SUL',      'SANTA CATARINA']
Length: 27, dtype: str

In [41]:
df_gasolina2014 = df_gasolina[(df_gasolina['ANO-MES'] == '2014-05') & (df_gasolina['ESTADO'] == 'SAO PAULO')]
df_gasolina2014['PREÇO MÉDIO REVENDA'].mean()

np.float64(2.8822)

### 10. Você conseguiria descobrir em qual(quais) estado(s) a gasolina ultrapassou a barreira dos R$ 5,00? E quando isso ocorreu?

In [45]:
df_maior = df_gasolina[df_gasolina['PREÇO MÉDIO REVENDA'] > 5.0]
df_maior.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO-MES
98201,98201,2018-05-20,2018-05-26,NORTE,ACRE,GASOLINA COMUM,39,R$/l,5.053,0.184,4.930,5.459,0.797,0.036,4.256,0.132,4.07,4.4685,0.031,2018-05
98347,98347,2018-05-27,2018-06-02,NORTE,ACRE,GASOLINA COMUM,11,R$/l,5.035,0.133,4.890,5.400,0.799,0.026,4.236,0.152,4.07,4.4542,0.036,2018-06
98493,98493,2018-06-03,2018-06-09,NORTE,ACRE,GASOLINA COMUM,39,R$/l,5.038,0.197,4.840,5.459,0.664,0.039,4.374,0.084,4.2316,4.576,0.019,2018-06
98511,98511,2018-06-03,2018-06-09,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,414,R$/l,5.016,0.144,4.459,5.599,0.541,0.029,4.475,0.108,4.1667,4.8321,0.024,2018-06
98646,98646,2018-06-10,2018-06-16,NORTE,ACRE,GASOLINA COMUM,38,R$/l,5.031,0.206,4.840,5.459,0.686,0.041,4.345,0.081,4.2149,4.518,0.019,2018-06

In [46]:
df_maior['ANO-MES'].unique()

<PeriodArray>
['2018-05', '2018-06', '2018-07', '2018-08', '2018-09', '2018-10', '2018-11',
 '2018-12', '2019-05', '2019-06', '2019-07', '2020-01', '2020-02', '2020-03',
 '2020-12', '2021-01', '2021-02', '2021-03', '2021-04', '2021-05']
Length: 20, dtype: period[M]

In [47]:
df_maior['ESTADO'].unique()

<StringArray>
[               'ACRE',      'RIO DE JANEIRO',           'TOCANTINS',
 'RIO GRANDE DO NORTE',    'DISTRITO FEDERAL',             'ALAGOAS',
               'BAHIA',               'CEARA',  'MATO GROSSO DO SUL',
        'MINAS GERAIS',                'PARA',               'PIAUI',
   'RIO GRANDE DO SUL',            'AMAZONAS',      'ESPIRITO SANTO',
               'GOIAS',            'MARANHAO',             'PARAIBA',
          'PERNAMBUCO',            'RONDONIA',      'SANTA CATARINA',
             'SERGIPE',         'MATO GROSSO',              'PARANA',
             'RORAIMA',           'SAO PAULO']
Length: 26, dtype: str

### 11. Qual a média de preço dos estados da região sul em 2012?

In [54]:
df_2012 = df_gasolina[(df_gasolina['DATA FINAL'].dt.year == 2012) & (df_gasolina['REGIÃO'] == 'SUL')]
df_2012['PREÇO MÉDIO REVENDA'].mean()

np.float64(2.7214423076923073)

### 12. Você conseguiria obter uma tabela contendo a variação percentual ano a ano para o estado do Rio de Janeiro?

In [ ]:
df_rj = df_gasolina[df_gasolina['ESTADO'] == 'RIO DE JANEIRO']

precos_ano_rj = df_rj.groupby(df_rj['DATA FINAL'].dt.year)['PREÇO MÉDIO REVENDA'].mean()

variacao_ano_a_ano = precos_ano_rj.pct_change() * 100

variacao_ano_a_ano

DATA FINAL
2004          NaN
2005     7.672813
2006     9.526138
2007    -1.143471
2008     0.578728
2009     0.716575
2010     3.228425
2011     6.983551
2012     0.710588
2013     4.999090
2014     4.562701
2015    12.941899
2016    10.749637
2017     4.711187
2018    18.349897
2019     0.000396
2020    -1.932005
2021    17.379353
Name: PREÇO MÉDIO REVENDA, dtype: float64

### DESAFIO: Crie uma tabela contendo uma serie temporal com a diferença absoluta e percentual entre os valores mais baratos e caros. Apresente também ao lado os estados na qual os maiores e menores preços foram registrados.

In [57]:
precos_estados_ano = df_gasolina.groupby(['ESTADO', df_gasolina['DATA FINAL'].dt.year])['PREÇO MÉDIO REVENDA'].mean()


variacao_todos = precos_estados_ano.groupby(level=0).pct_change() * 100

variacao_2021 = variacao_todos.xs(2021, level=1)

variacao_2021.sort_values(ascending=False)

ESTADO
DISTRITO FEDERAL       25.663006
AMAPA                  25.368222
RORAIMA                23.145290
PARAIBA                22.822904
ESPIRITO SANTO         22.812247
MATO GROSSO DO SUL     21.258634
RIO GRANDE DO SUL      20.703688
PARANA                 20.547302
GOIAS                  20.490972
RONDONIA               20.265741
PIAUI                  20.150316
ACRE                   19.647755
TOCANTINS              19.601308
ALAGOAS                19.539109
RIO GRANDE DO NORTE    19.281159
PERNAMBUCO             18.824004
MINAS GERAIS           18.699880
MARANHAO               18.657789
SANTA CATARINA         18.494211
BAHIA                  18.358805
SAO PAULO              18.312486
SERGIPE                17.914792
CEARA                  17.909954
PARA                   17.656034
RIO DE JANEIRO         17.379353
AMAZONAS               16.306958
MATO GROSSO            16.300653
Name: PREÇO MÉDIO REVENDA, dtype: float64